### PR TITLE
Fix path to XawInit.h

### LINKED ISSUE #6: Makefile issues
When running the command `make World` I received a fatal error. The error was because it couldn't find the file "X11/Xaw/XawInit.h". After tracking down the location of XawInit.h in "x11/iraf/include/X11/Xaw3d/", I resolved this by `mkdir Xaw` when in the X11 directory. Then I copied the contents of "Xaw3d" into "Xaw" with the command `cp Xaw3d/* Xaw/`. `make World` ran successfully after this and I found the executable in "x11iraf/bin".

So If anyone else runs into this problem this should solve it.

This is a minor issue, but it did give me some trouble to find the fix. If this could be addressed in an update I know it would be appreciated by beginner iraf users like myself :)

### PR DESCRIPTION
**Pull request by olebole**
There are actually *two* files with that name in the repository:

 * `xaw3d/XawInit.h`
 * `obm/ObmW/Xraw/XawInit.h`

They have a comon origin; however the xaw3d variant seems newer. However, since all other files in `obm/ObmW` refer to the obm variant, this is also probably the right version here.

This fixes #6. @joezepeda, could you test this and give some feedback?

### CODE REVIEW

**Comment by joezepeda** [comment]
I removed x11iraf, but I got the following fatal error despite making the changes:
"HTML.c:62:10: fatal error: X11/Xaw/Scrollbar.h: No such file or directory
 #include <X11/Xaw/Scrollbar.h>".

**Comment by olebole** [comment]
I now tried to fix all remaining wrong references. Could you try again?

**Comment by joezepeda** [comment]
I tried again and got the same error message.

**Comment by olebole** [comment]
Can you tell me your configuration? Which OS, which packages do you have installed? Especially, which development libraries?

**Comment by joezepeda** [comment]
I am running this on Ubuntu 18.04. I am not sure specifically what you mean by development libraries and packages.

**Comment by olebole** [comment]
I will probably not apply this, since it seems that the major cause of the problem is that `libxaw7-dev` was not installed. With this package, everything should work fine.

**Pull request closed without merging**
